/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;

/**
 *
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 *
 * @author Harshit
 */
public class Infra extends javax.swing.JFrame {

    /**
     * Creates new form Infra
     */
    public Infra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        room = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        roomono = new javax.swing.JLabel();
        roomtext = new javax.swing.JTextField();
        floorno = new javax.swing.JLabel();
        floortext = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        registerbutton = new javax.swing.JButton();
        roombutt = new javax.swing.JRadioButton();
        floorbutt = new javax.swing.JRadioButton();
        printproblem = new javax.swing.JLabel();
        steps = new javax.swing.JLabel();
        WARNING = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        backbut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(159, 28, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(159, 28, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, -1, -1));

        jLabel1.setBackground(new java.awt.Color(159, 28, 51));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INFRASTRUCTURE GRIEVANCE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 47, 400, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel3.setText("  ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 94));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 684));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roomono.setBackground(new java.awt.Color(255, 159, 67));
        roomono.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        roomono.setForeground(new java.awt.Color(159, 28, 51));
        roomono.setText("ROOM NO:");
        roomono.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                roomonoPropertyChange(evt);
            }
        });
        jPanel3.add(roomono, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 33, -1, -1));

        roomtext.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        roomtext.setForeground(new java.awt.Color(159, 28, 51));
        roomtext.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.red, java.awt.Color.lightGray, java.awt.Color.white));
        roomtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                roomtextFocusGained(evt);
            }
        });
        roomtext.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                roomtextInputMethodTextChanged(evt);
            }
        });
        roomtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomtextActionPerformed(evt);
            }
        });
        roomtext.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                roomtextPropertyChange(evt);
            }
        });
        roomtext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                roomtextKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                roomtextKeyTyped(evt);
            }
        });
        jPanel3.add(roomtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 71, 200, 33));

        floorno.setBackground(new java.awt.Color(255, 159, 67));
        floorno.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        floorno.setForeground(new java.awt.Color(159, 28, 51));
        floorno.setText("FLOOR:");
        floorno.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                floornoPropertyChange(evt);
            }
        });
        jPanel3.add(floorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 28, -1, -1));

        floortext.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        floortext.setForeground(new java.awt.Color(159, 28, 51));
        floortext.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.red, java.awt.Color.lightGray, java.awt.Color.white));
        floortext.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                floortextPropertyChange(evt);
            }
        });
        floortext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                floortextKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                floortextKeyTyped(evt);
            }
        });
        jPanel3.add(floortext, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 200, 33));

        jComboBox1.setBackground(new java.awt.Color(159, 28, 51));
        jComboBox1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "FAN ", "LIGHT", "AIR CONDITIONER", "BENCHES", "DUSTBIN", "PROJECTOR", "OTHERS", " " }));
        jComboBox1.setBorder(null);
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox1.setMinimumSize(new java.awt.Dimension(191, 30));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox1PropertyChange(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jComboBox1KeyTyped(evt);
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 200, 34));

        jComboBox2.setBackground(new java.awt.Color(159, 28, 51));
        jComboBox2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "DRINKING WATER", "ELEVATOR", "CLOSED WASHROOM", "OTHERS" }));
        jComboBox2.setBorder(null);
        jComboBox2.setPreferredSize(new java.awt.Dimension(191, 30));
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jComboBox2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox2PropertyChange(evt);
            }
        });
        jPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 200, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(159, 28, 51));
        jTextArea2.setRows(5);
        jTextArea2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.red, java.awt.Color.black, java.awt.Color.lightGray, java.awt.Color.white));
        jTextArea2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea2MouseClicked(evt);
            }
        });
        jTextArea2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextArea2PropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 875, 110));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(159, 28, 51));
        jLabel4.setText("ENTER IF ANY SUGGESTIONS:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        registerbutton.setBackground(new java.awt.Color(159, 28, 51));
        registerbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        registerbutton.setForeground(new java.awt.Color(255, 255, 255));
        registerbutton.setText("REGISTER");
        registerbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.red, java.awt.Color.lightGray, java.awt.Color.white));
        registerbutton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerbuttonFocusLost(evt);
            }
        });
        registerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbuttonActionPerformed(evt);
            }
        });
        registerbutton.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                registerbuttonPropertyChange(evt);
            }
        });
        registerbutton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                registerbuttonKeyPressed(evt);
            }
        });
        jPanel3.add(registerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 447, -1, -1));

        roombutt.setBackground(new java.awt.Color(255, 255, 255));
        room.add(roombutt);
        roombutt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        roombutt.setForeground(new java.awt.Color(159, 28, 51));
        roombutt.setText("ROOM");
        roombutt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        roombutt.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                roombuttStateChanged(evt);
            }
        });
        roombutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roombuttActionPerformed(evt);
            }
        });
        roombutt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                roombuttPropertyChange(evt);
            }
        });
        roombutt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                roombuttKeyPressed(evt);
            }
        });
        jPanel3.add(roombutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 159, 35));

        floorbutt.setBackground(new java.awt.Color(255, 255, 255));
        room.add(floorbutt);
        floorbutt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        floorbutt.setForeground(new java.awt.Color(159, 28, 51));
        floorbutt.setText("FLOOR");
        floorbutt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                floorbuttMouseClicked(evt);
            }
        });
        floorbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorbuttActionPerformed(evt);
            }
        });
        jPanel3.add(floorbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 159, 37));

        printproblem.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        printproblem.setForeground(new java.awt.Color(159, 28, 51));
        printproblem.setText("                                             ");
        jPanel3.add(printproblem, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 850, 40));

        steps.setFont(new java.awt.Font("Arial", 2, 13)); // NOI18N
        steps.setForeground(new java.awt.Color(159, 28, 51));
        steps.setText("*SELECT ROOM/FLOOR , SPECIFY THE ROOM/FLOOR , WRITE DETAILED GRIEVANCE OR SUGGESTION , REGISTER GRIEVANCE*");
        jPanel3.add(steps, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 920, -1));

        WARNING.setFont(new java.awt.Font("Arial", 3, 13)); // NOI18N
        WARNING.setForeground(new java.awt.Color(159, 28, 51));
        WARNING.setText("*MAKE SURE TO USE APPROPRIATE WORDS*");
        WARNING.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                WARNINGPropertyChange(evt);
            }
        });
        jPanel3.add(WARNING, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 490, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(159, 28, 51));
        jLabel5.setText("   ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 525, 40));

        backbut.setBackground(new java.awt.Color(255, 255, 255));
        backbut.setIcon(new javax.swing.ImageIcon("E:\\tpc\\project\\ICONS\\back.png")); // NOI18N
        backbut.setBorder(null);
        backbut.setMargin(new java.awt.Insets(50, 50, 50, 50));
        backbut.setMaximumSize(new java.awt.Dimension(50, 50));
        backbut.setMinimumSize(new java.awt.Dimension(50, 50));
        backbut.setPreferredSize(new java.awt.Dimension(50, 50));
        backbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbutActionPerformed(evt);
            }
        });
        jPanel3.add(backbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, -1, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 101, -1, 575));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void roomtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomtextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_roomtextActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
//        int i=floortext.getText().length();
        
        
        String item1=jComboBox1.getSelectedItem()+"";
        String m1=roomtext.getText();

        if (item1.equals("SELECT")){
        printproblem.setText(" SELECT A VALID ITEM "); 
        registerbutton.setVisible(false);
        }

        else if (item1.equals("OTHERS")) {
            printproblem.setText("PLEASE SPECIFY IN THE TEXTBOX FOR THE Room Number "+m1);
            //registerbutton.setVisible(false);
        }
        else if (item1.equals("")){
            printproblem.setText("Enter the Room Number");
            registerbutton.setVisible(false);
        }
        else {printproblem.setText(item1+" is a problem in Room "+m1);
        registerbutton.setVisible(true);}
                String room= roomtext.getText();
        int len=room.length();
        if(len<3)
        {
            registerbutton.setVisible(false);
            printproblem.setText("Enter a three digit room number");
        }
        

//        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void registerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbuttonActionPerformed
DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
   LocalDateTime now = LocalDateTime.now(); 

PreparedStatement stat;

 try
        {            
            Class.forName("com.mysql.jdbc.Driver");
           Connection con = (Connection) DriverManager.getConnection("Enter your mysql link");                                                                                 
           
       
            String sql = "insert into infra values (?, ?,?,?,?,?)";
                  
//            int y= slider.getValue();
//             String s= in2.getText(); 
//             String t= out1.getText();
//             String grd = Integer.toString(y);
             Random rand = new Random(); 
             int rand_int1 = rand.nextInt(10000);
             String rand_str = Integer.toString(rand_int1);
             PreparedStatement pstmt = con.prepareStatement (sql);
          pstmt.setString(1,LOGIN.jTextField1.getText());
             pstmt.setString(2,dtf.format(now) );
             pstmt.setString(3,printproblem.getText());
              pstmt.setString(4,jTextArea2.getText());
              pstmt.setString(5,rand_str);   
              pstmt.setString(6,"PENDING");   
                pstmt.executeUpdate();
                  
                con.close();
               
        }
catch(SQLException se){
             se.printStackTrace();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewJFrame12.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
      
 
        jLabel5.setText("GRIEVANCES AND SUGGESTIONS REGISTERED!");
    }//GEN-LAST:event_registerbuttonActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        String item2=jComboBox2.getSelectedItem()+"";
         String m2=floortext.getText();
         if (item2.equals("SELECT")){
        printproblem.setText(" SELECT A VALID ITEM "); 
        registerbutton.setVisible(false);
        }

        else if (item2.equals("OTHERS")) {
            printproblem.setText("PLEASE SPECIFY IN THE TEXTBOX FOR Floor Number "+m2);
           // registerbutton.setVisible(false);
        }
        else if (item2.equals("")){
            printproblem.setText("Enter the Floor Number");
            registerbutton.setVisible(false);
            
        }
        else {printproblem.setVisible(true);
            printproblem.setText(item2+" is a problem in Floor "+m2);
        registerbutton.setVisible(true);}
         
        
       
                
                String floor= floortext.getText();
        int len=floor.length();
        if(len>1)
        {
            registerbutton.setVisible(false);
            printproblem.setText("Enter a single digit floor number");
        }
        int i=Integer.parseInt(floortext.getText());
        if(i==0&&i>6){
                        printproblem.setText("Enter a valid floor number");
        registerbutton.setVisible(false);
            
        }

        
        

//        
                
        
                
        
            
            
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void roombuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roombuttActionPerformed
        jComboBox2.setVisible(false);
        floorno.setVisible(false);
        floortext.setVisible(false);
        jTextArea2.setVisible(true);
        //registerbutton.setVisible(true);
        printproblem.setText(" ");
        jTextArea2.setText(" ");
        jComboBox1.setVisible(false);
        roomono.setVisible(true);
        roomtext.setVisible(true);
        floortext.setText("");
        floortext.setEditable(true);
        roomtext.setEditable(true);
      

       
             
        
    }//GEN-LAST:event_roombuttActionPerformed

    private void roombuttPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_roombuttPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_roombuttPropertyChange

    private void roombuttStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_roombuttStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_roombuttStateChanged

    private void floorbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floorbuttActionPerformed
        jComboBox1.setVisible(false);
        roomono.setVisible(false);
        roomtext.setVisible(false);
        jTextArea2.setVisible(true);
        //registerbutton.setVisible(true);
        printproblem.setText(" ");
        jComboBox2.setVisible(false);
        floorno.setVisible(true);
        floortext.setVisible(true);
        jTextArea2.setText(" ");
        roomtext.setText("");
        roomtext.setEditable(true);
        floortext.setEditable(true);
       
    }//GEN-LAST:event_floorbuttActionPerformed

    private void roomonoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_roomonoPropertyChange
        // TODO add your handling code here:
        roomono.setVisible(false);
    }//GEN-LAST:event_roomonoPropertyChange

    private void roomtextPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_roomtextPropertyChange
        // TODO add your handling code here:
        roomtext.setVisible(false);
    }//GEN-LAST:event_roomtextPropertyChange

    private void jComboBox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox1PropertyChange
        // TODO add your handling code here:
        jComboBox1.setVisible(false);
    }//GEN-LAST:event_jComboBox1PropertyChange

    private void floortextPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_floortextPropertyChange
        // TODO add your handling code here:
        floortext.setVisible(false);
    }//GEN-LAST:event_floortextPropertyChange

    private void floornoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_floornoPropertyChange
        // TODO add your handling code here:
        floorno.setVisible(false);
    }//GEN-LAST:event_floornoPropertyChange

    private void jComboBox2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox2PropertyChange
        // TODO add your handling code here:
        jComboBox2.setVisible(false);
    }//GEN-LAST:event_jComboBox2PropertyChange

    private void jTextArea2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextArea2PropertyChange
        // TODO add your handling code here:
        jTextArea2.setVisible(false);
    }//GEN-LAST:event_jTextArea2PropertyChange

    private void registerbuttonPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_registerbuttonPropertyChange
        // TODO add your handling code here:
        registerbutton.setVisible(false);
    }//GEN-LAST:event_registerbuttonPropertyChange

    private void jTextArea2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea2MouseClicked
        // TODO add your handling code here:
//        registerbutton.setVisible(true);
//        WARNING.setVisible(true);
//        roomtext.setEditable(false);
//        floortext.setEditable(false);
//        roomtext.setVisible(true);
//        floortext.setVisible(true);
        
//            roomtext.setVisible(false);
//            jComboBox1.setVisible(false);
//            roomono.setVisible(false);
//        
//        
//        
//                        floortext.setVisible(false);
//            jComboBox2.setVisible(false);
//            floorno.setVisible(false);

            
        
    }//GEN-LAST:event_jTextArea2MouseClicked

    private void WARNINGPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_WARNINGPropertyChange
        // TODO add your handling code here:
        WARNING.setVisible(false);
        
    }//GEN-LAST:event_WARNINGPropertyChange

    private void roombuttKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_roombuttKeyPressed
        // TODO add your handling code here:
        WARNING.setVisible(false);
        
       
    }//GEN-LAST:event_roombuttKeyPressed

    private void roomtextInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_roomtextInputMethodTextChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_roomtextInputMethodTextChanged

    private void roomtextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_roomtextKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c== KeyEvent.VK_BACKSPACE) || (c==KeyEvent.VK_DELETE))
            evt.consume();
        
        
    }//GEN-LAST:event_roomtextKeyTyped

    private void floortextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_floortextKeyTyped
        // TODO add your handling code here:
                char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c== KeyEvent.VK_BACKSPACE) || (c==KeyEvent.VK_DELETE))
            evt.consume();

    }//GEN-LAST:event_floortextKeyTyped

    private void registerbuttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registerbuttonKeyPressed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_registerbuttonKeyPressed

    private void registerbuttonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerbuttonFocusLost

    }//GEN-LAST:event_registerbuttonFocusLost

    private void roomtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_roomtextFocusGained

    }//GEN-LAST:event_roomtextFocusGained

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox2MouseClicked

    private void floorbuttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_floorbuttMouseClicked
        // TODO add your handling code here:
        WARNING.setVisible(false);

    }//GEN-LAST:event_floorbuttMouseClicked

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void roomtextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_roomtextKeyPressed
        // TODO add your handling code here:
        jComboBox1.setVisible(true);
        
        String room= roomtext.getText();
        int len=room.length();
        char c=evt.getKeyChar();
        if (evt.getKeyChar()>='0'&&evt.getKeyChar()<='9'){
            if(len<3)
            {
                roomtext.setEditable(true);
                printproblem.setText("");
                registerbutton.setVisible(true);
            }

            else

            {
                printproblem.setText("Enter a three digit room number");
               roomtext.setEditable(false);
                roomtext.setVisible(true);
                registerbutton.setVisible(false);
            }
        }else{

            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACKSPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                roomtext.setEditable(true);

        }else {
                printproblem.setText("Input only in digits");
                
              //roomtext.setEditable(false);
            }

                
                }
    }//GEN-LAST:event_roomtextKeyPressed

    private void floortextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_floortextKeyPressed
        // TODO add your handling code here:
        //registerbutton.setVisible(true);
        jComboBox2.setVisible(true);
        
                String floor= floortext.getText();
        int len=floor.length();
        char c=evt.getKeyChar();
        if (evt.getKeyChar()>='0'&&evt.getKeyChar()<='6'){
        
            if(len<1)
            {
                floortext.setEditable(true);
                printproblem.setText("");
                registerbutton.setVisible(true);
            }
            else
            {
                printproblem.setText("Enter a single digit floor number");
              floortext.setEditable(false);
                floortext.setVisible(true);
                registerbutton.setVisible(false);
                
            }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACKSPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                floortext.setEditable(true);
                

        }
            else {
                printproblem.setText("Input only in digits");
                //registerbutton.setVisible(false);
                
               //floortext.setEditable(false);
            }

                
                }
    }//GEN-LAST:event_floortextKeyPressed

    private void jComboBox1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1KeyTyped

    private void backbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbutActionPerformed
       F2 o4= new F2();
         o4.show();
         this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_backbutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Infra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Infra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Infra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Infra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Infra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WARNING;
    private javax.swing.JButton backbut;
    private javax.swing.JRadioButton floorbutt;
    private javax.swing.JLabel floorno;
    private javax.swing.JTextField floortext;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel printproblem;
    private javax.swing.JButton registerbutton;
    private javax.swing.ButtonGroup room;
    private javax.swing.JRadioButton roombutt;
    private javax.swing.JLabel roomono;
    private javax.swing.JTextField roomtext;
    private javax.swing.JLabel steps;
    // End of variables declaration//GEN-END:variables
}
